version: '3'
services:
  redis-db:  # container name
    image: redis:alpine
    volumes:
      - data-db:/data:rw

  portal-app:  # container name
    build: web
    environment:
      - APP_PORT=8888
      - REDIS_HOST=redis-db
    volumes:
      - ./templates:/app/templates:ro
    depends_on:
      - redis-db

  nginx:
    image: nginx:alpine
    ports: 
      - 8000:8000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - portal-app

volumes:
  data-db:
    driver: local

